# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title The main function to calculate continuous NKDE
#'
#' @param edge_list A list of edges, accessible by their names
#' @param neighbour_list a list of the neighbours of each node
#' @param events a numeric vector of the node id of each event
#' @param weights a numeric vector of the weight of each event
#' @param samples a DataFrame of the samples (with spatial coordinates and belonging edge)
#' @param bw the kernel bandwidth
#' @param kernel_func the function to calculate the kernel from distance
#' @param nodes a DataFrame representing the nodes of the graph (with spatial coordinates)
#' @param line_list a DataFrame representing the lines of the graph
#' @param max_depth the maximum recursion depth (after which recursion is stopped)
#' @param verbose a boolean indicating if the function must print its progress
#' @return a DataFrame with two columns : the kernel values (sum_k) and the number of event reaching each samples (n)
#' @export
#'
continuous_nkde_cpp <- function(edge_list, neighbour_list, events, weights, samples, bw, kernel_func, nodes, line_list, max_depth, verbose) {
    .Call('_spNetworkCpp_continuous_nkde_cpp', PACKAGE = 'spNetworkCpp', edge_list, neighbour_list, events, weights, samples, bw, kernel_func, nodes, line_list, max_depth, verbose)
}

#' @title The main function to calculate discontinuous NKDE
#'
#' @param edge_list A list of edges, accessible by their names
#' @param neighbour_list a list of the neighbours of each node
#' @param events a numeric vector of the node id of each event
#' @param weights a numeric vector of the weight of each event
#' @param samples a DataFrame of the samples (with spatial coordinates and belonging edge)
#' @param bw the kernel bandwidth
#' @param kernel_func the function to calculate the kernel from distance
#' @param nodes a DataFrame representing the nodes of the graph (with spatial coordinates)
#' @param line_list a DataFrame representing the lines of the graph
#' @param verbose a boolean indicating if the function must print its progress
#' @return a DataFrame with two columns : the kernel values (sum_k) and the number of event reaching each samples (n)
#' @export
#'
discontinuous_nkde_cpp <- function(edge_list, neighbour_list, events, weights, samples, bw, kernel_func, nodes, line_list, verbose) {
    .Call('_spNetworkCpp_discontinuous_nkde_cpp', PACKAGE = 'spNetworkCpp', edge_list, neighbour_list, events, weights, samples, bw, kernel_func, nodes, line_list, verbose)
}

